services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    ports:
      - "54330:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest-postdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
